import { AuthProvider } from "@/context/AuthContext";
import { Providers } from "../../context/providers";
import { Suspense } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="en">
    //   <body>
    <Suspense fallback={<div>Loading...</div>}>
      <Providers>
        <AuthProvider>{children}</AuthProvider>
      </Providers>
    </Suspense>
    //   </body>
    // </html>
  );
}
