import { AuthProvider } from "@/context/AuthContext";
import { Providers } from "../../context/providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="en">
    //   <body>
    <Providers>
      <AuthProvider>{children}</AuthProvider>
    </Providers>
    //   </body>
    // </html>
  );
}
